// src/pages/tools/remove-newline/index.tsx
import { useState } from "react";
import { CopyButton, ClearButton, Button } from "../../../components/Buttons";
import { PageTitle } from "../../../components/PageTitle";
import { Textarea } from "../../../components/Textarea";

export default function RemoveNewline() {
  const [text, setText] = useState("");

  const removeAllNewlines = () => {
    setText(text.replace(/[\n\r]/g, ""));
  };

  const clear = () => {
    setText("");
  };

  const copy = () => {
    navigator.clipboard.writeText(text).then(
      () => alert(`Copied!`),
      (err) => alert(`Copy failed! ${err}`)
    );
  };

  return (
    <>
      <PageTitle title="Remove Newline" />

      <div className="card">
        <header className="card-header flex justify-end">
          <CopyButton onClick={copy} />
          <ClearButton onClick={clear} />
        </header>

        <div className="card-body space-y-4">
          <Textarea
            value={text}
            onChange={(e: any) => setText(e.target.value)}
          />

          <div>
            <Button title="Remove All Newlines" onClick={removeAllNewlines} />
          </div>
        </div>
      </div>
    </>
  );
}

// src/pages/RemoveNewline.svelte
<script>
    import ClearButton from "../lib/buttons/Clear.svelte";
    import CopyButton from "../lib/buttons/Copy.svelte";
    import PageTitle from "../lib/PageTitle.svelte";
    
    let text = "";

    const removeAllNewlines = () => {
        text = text.replace(/[\n\r]/g, "");
    };

    const clear = () => {
        text = "";
    };

    const copy = () => {
        navigator.clipboard.writeText(text).then(
            () => alert(`Copied!`),
            (err) => alert(`Copy failed! ${err}`)
        );
    };
</script>

<PageTitle title="Remove Newline" />

<div class="card">
    <header class="card-header flex justify-end">
        <CopyButton on:click={copy} />
        <ClearButton on:click={clear} />
    </header>

    <div class="card-body space-y-4">
        <textarea bind:value={text} rows="15" placeholder="Write something..."></textarea>

        <div>
            <button on:click={removeAllNewlines}>Remove All Newlines</button>
        </div>
    </div>
</div>
