// src/pages/RemoveNewline/index.tsx
import { useState } from "react";
import { ClearButton } from "../../components/Buttons/ClearButton";
import { CopyButton } from "../../components/Buttons/CopyButton";

export const RemoveNewline = () => {
  const [text, setText] = useState("");

  const removeAllNewlines = () => {
    setText(text.replace(/[\n\r]/g, ""));
  };

  const clear = () => {
    setText("");
  };

  const copy = () => {
    navigator.clipboard
      .writeText(text)
      .then(() => alert(`Copied!`))
      .catch((error) => alert(`Copy failed! ${error}`));
  };

  return (
    <>
      <header className="text-lg font-medium">Remove Newline</header>

      <div className="card">
        <header className="card-header flex justify-end">
          <CopyButton onClick={copy} />
          <ClearButton onClick={clear} />
        </header>

        <div className="card-body space-y-4">
          <textarea
            onChange={(e) => setText(e.target.value)}
            value={text}
            rows={20}
            className="textarea"
            placeholder="Write something..."
          ></textarea>

          <div>
            <button
              className="btn-primary"
              title="capitalize"
              onClick={removeAllNewlines}
            >
              Remove All Newlines
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

// src/pages/RemoveNewline.svelte
<script>
    import ClearButton from "../lib/buttons/Clear.svelte";
    import CopyButton from "../lib/buttons/Copy.svelte";
    import PageTitle from "../lib/PageTitle.svelte";
    
    let text = "";

    const removeAllNewlines = () => {
        text = text.replace(/[\n\r]/g, "");
    };

    const clear = () => {
        text = "";
    };

    const copy = () => {
        navigator.clipboard.writeText(text).then(
            () => alert(`Copied!`),
            (err) => alert(`Copy failed! ${err}`)
        );
    };
</script>

<PageTitle title="Remove Newline" />

<div class="card">
    <header class="card-header flex justify-end">
        <CopyButton on:click={copy} />
        <ClearButton on:click={clear} />
    </header>

    <div class="card-body space-y-4">
        <textarea bind:value={text} rows="15" placeholder="Write something..."></textarea>

        <div>
            <button on:click={removeAllNewlines}>Remove All Newlines</button>
        </div>
    </div>
</div>
