// src/pages/SqlFormatter.jsx
import { useState } from "react";
import { PageTitle, Textarea, Select } from "../components";
import { CopyButton, ClearButton, PrimaryButton } from "../components/buttons";
import { format } from 'sql-formatter';
import { isEmpty } from "../helpers";

export default function SqlFormatter() {
    const [text, setText] = useState("");
    const [formatTo, setFormatTo] = useState("");

    const runFormat = () => {
        if (isEmpty(formatTo)) {
            alert("Choose database type to format!");
            return;
        }

        const result = format(text, { language: formatTo, keywordCase: "upper" })

        setText(result);
    };

    const clear = () => {
        setText("");
        setFormatTo("");
    };

    const copy = () => {
        navigator.clipboard.writeText(text).then(
            () => alert(`Copied!`),
            (err) => alert(`Copy failed! ${err}`)
        );
    };

    return (
        <>
            <PageTitle title="SQL Formatter" />

            <div className="card mb-4">
                <header className="card-header flex justify-between gap-2">
                    <Select
                        value={formatTo}
                        onChange={(e) => setFormatTo(e.target.value)}
                        placeholder="convert to"
                        options={[
                            { id: 1, title: "SQL Server", value: "tsql" },
                            { id: 2, title: "PostgreSQL", value: "postgresql" },
                            { id: 3, title: "MySQL", value: "mysql" },
                            { id: 4, title: "MariaDB", value: "mariadb" },

                        ]}
                    />

                    <div className="flex">
                        <CopyButton onClick={copy} />
                        <ClearButton onClick={clear} />
                    </div>
                </header>

                <div className="card-body space-y-4">
                    <Textarea
                        onChange={(e) => setText(e.target.value)}
                        value={text}
                    />

                    <div>
                        <PrimaryButton title="Format" onClick={runFormat} />
                    </div>
                </div>
            </div>
        </>
    );
}

// src/pages/SqlFormatter.svelte

<script>
    import PageTitle from "../lib/PageTitle.svelte";
    import ClearButton from "../lib/buttons/Clear.svelte";
    import CopyButton from "../lib/buttons/Copy.svelte";
    import { format } from 'sql-formatter';
    import { isEmpty } from "../assets/js/helper.js";
    
    let text = "";
    let formatTo = "";

    const execute = () => {
        if (isEmpty(formatTo)) {
            alert("Choose database type to format!");
            return;
        }

        text = format(text, { language: formatTo, keywordCase: "upper" });
    };

    const clear = () => {
        text = "";
        formatTo = "";
    };

    const copy = () => {
        navigator.clipboard.writeText(text).then(
            () => alert(`Copied!`),
            (err) => alert(`Copy failed! ${err}`)
        );
    };
</script>

<PageTitle title="SQL Formatter" />

<div class="card mb-4">
    <header class="card-header flex justify-between gap-2">
        <select bind:value={formatTo}>
            <option value="" disabled selected>convert to</option>
            <option value="tsql">SQL Server</option>
            <option value="postgresql">PostgreSQL</option>
            <option value="mysql">MySQL</option>
            <option value="mariadb">MariaDB</option>
        </select>

        <div class="flex">
            <CopyButton on:click={copy} />
            <ClearButton on:click={clear} />
        </div>
    </header>

    <div class="card-body space-y-4">
        <textarea bind:value={text} rows="15" placeholder="Write something..."></textarea>

        <div>
            <button on:click={execute} class="btn-primary">Format</button>
        </div>
    </div>
</div>
