// src/pages/TextTransform.jsx
import { useState } from "react";
import { PrimaryButton, CopyButton, ClearButton } from "../components/buttons";
import { PageTitle, Textarea } from "../components";

export default function TextTransform() {
    const [text, setText] = useState("");

    const capitalize = () => {
        const arr_text = text.toLowerCase().split(" ");

        for (let i = 0; i < arr_text.length; i++) {
            arr_text[i] = arr_text[i][0].toUpperCase() + arr_text[i].substr(1);
        }

        setText(arr_text.join(" "));
    };

    const lowercase = () => {
        setText(text.toLowerCase());
    };

    const uppercase = () => {
        setText(text.toUpperCase());
    };

    const clear = () => {
        setText("");
    };

    const copy = () => {
        navigator.clipboard.writeText(text).then(
            () => alert(`Copied!`),
            (err) => alert(`Copy failed! ${err}`)
        );
    };

    return (
        <>
            <PageTitle title="Text Transforms" />

            <div className="card mb-4">
                <header className="card-header flex justify-end">
                    <CopyButton onClick={copy} />
                    <ClearButton onClick={clear} />
                </header>

                <div className="card-body space-y-4">
                    <Textarea
                        onChange={(e) => setText(e.target.value)}
                        value={text}
                    />

                    <div className="flex gap-2">
                        <PrimaryButton title="Capitalize" onClick={capitalize} />
                        <PrimaryButton title="Lowercase" onClick={lowercase} />
                        <PrimaryButton title="Uppercase" onClick={uppercase} />
                    </div>
                </div>
            </div>
        </>
    );
}

// src/pages/TextTransform.svelte
<script>
    import PageTitle from "../lib/PageTitle.svelte";
    import ClearButton from "../lib/buttons/Clear.svelte";
    import CopyButton from "../lib/buttons/Copy.svelte";

    let text = "";

    const capitalize = () => {
        const arr_text = text.toLowerCase().split(" ");

        for (let i = 0; i < arr_text.length; i++) {
            arr_text[i] = arr_text[i][0].toUpperCase() + arr_text[i].substr(1);
        }

        text = arr_text.join(" ");
    };

    const lowercase = () => {
        text = text.toLowerCase();
    };

    const uppercase = () => {
        text = text.toUpperCase();
    };

    const clear = () => {
        text = "";
    };

    const copy = () => {
        navigator.clipboard.writeText(text).then(
            () => alert(`Copied!`),
            (err) => alert(`Copy failed! ${err}`)
        );
    };
</script>

<PageTitle title="Text Transforms" />

<div class="card mb-4">
    <header class="card-header flex justify-end">
        <CopyButton on:click={copy} />
        <ClearButton on:click={clear} />
    </header>

    <div class="card-body space-y-4">
        <textarea bind:value={text} rows="15" placeholder="Write something..."></textarea>

        <div class="flex gap-2">
            <button on:click={capitalize} class="btn-primary">Capitalize</button>
            <button on:click={lowercase} class="btn-primary">Lowercase</button>
            <button on:click={uppercase} class="btn-primary">Uppercase</button>
        </div>
    </div>
</div>
