// src/App.svelte
<!-- App.svelte -->
<script>
    import { Router, Link, Route } from "svelte-routing";
    import Home from "./pages/Home.svelte";
    import ColorExtractor from "./pages/ColorExtractor.svelte";
    import ColorSimilarity from "./pages/ColorSimilarity.svelte";
    // import ExcelToSql from "./pages/ExcelToSql.svelte";
    import QrcodeScanner from "./pages/QrcodeScanner.svelte";
    import RemoveNewline from "./pages/RemoveNewline.svelte";
    import SqlFormatter from "./pages/SqlFormatter.svelte";
    import TextCount from "./pages/TextCount.svelte";
    import TextTransform from "./pages/TextTransform.svelte";
    import TextAdded from "./pages/TextAdded.svelte";
  
    export let url = "";
  </script>
  
  <Router {url}>
    <div class="w-full space-y-4 py-2 px-3">
        <Route path="/" component={Home} />
        <Route path="/color-extractor" component={ColorExtractor} />
        <Route path="/color-similarity" component={ColorSimilarity} />
        <!-- <Route path="/excel-to-sql" component={ExcelToSql} /> -->
        <Route path="/qrcode-scanner" component={QrcodeScanner} />
        <Route path="/remove-newline" component={RemoveNewline} />
        <Route path="/sql-formatter" component={SqlFormatter} />
        <Route path="/text-count" component={TextCount} />
        <Route path="/text-transform" component={TextTransform} />
        <Route path="/text-added" component={TextAdded} />
    </div>
  </Router>

// src/App.jsx
import { BrowserRouter, Routes, Route } from "react-router-dom";
import Layout from "./components/Layout";
import {
    Home, ColorExtractor, ColorSimilarity, ExcelToSql, GearCalc,
    QrcodeScanner, RemoveNewline, SqlFormatter, TextCount, TextTransform, TextAdded
} from "./pages";

function App() {
    return (
        <BrowserRouter>
            <Routes>
                <Route element={<Layout />}>
                    <Route path="/" element={<Home />} />
                    <Route path="/color-extractor" element={<ColorExtractor />} />
                    <Route path="/color-similarity" element={<ColorSimilarity />} />
                    <Route path="/excel-to-sql" element={<ExcelToSql />} />
                    <Route path="/gear-calc" element={<GearCalc />} />
                    <Route path="/qrcode-scanner" element={<QrcodeScanner />} />
                    <Route path="/remove-newline" element={<RemoveNewline />} />
                    <Route path="/sql-formatter" element={<SqlFormatter />} />
                    <Route path="/text-count" element={<TextCount />} />
                    <Route path="/text-transform" element={<TextTransform />} />
                    <Route path="/text-added" element={<TextAdded />} />
                </Route>
            </Routes>
        </BrowserRouter>

    );
}

export default App;
